# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e3ba6ac1c1d4bb27434ad86915608486611683bf58e3d5dc09c3a5a70998e19b08bda4c46f0ecb71e1b8fe6b761684332b54e15133bb39d8a1c6ef860a5396d4

test:
  secret_key_base: c71982332bc2ae70bd6a008ec96f5c2b6963085a331cd5daf4a17838cb1f2f81c1a8a65422f180665e934794e5241ba4c782cc05f5b90aa099006f6bac73fac5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
